name = "MyAwesomePackage"
uuid = "cdc77f3c-276b-428e-8c7d-158c58a901d6"
authors = ["myusername <myusername@modernjuliaworkflows.github> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
