name = "MyAwesomePackage"
uuid = "716e21bb-4e2d-4b51-bb18-22745186fd0f"
authors = ["myusername <myusername@modernjuliaworkflows.github> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
