name = "MyAwesomePackage"
uuid = "9a46dbd3-34af-49fc-88c9-8dba811cadb2"
authors = ["myusername <myusername@modernjuliaworkflows.github> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
