name = "MyAwesomePackage"
uuid = "a4621eb3-dc11-49d6-b959-1a0d4b3ba392"
authors = ["myusername <myusername@modernjuliaworkflows.github> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
